### PR TITLE
Add inline-script

### PR DESCRIPTION
**Pull request by piquark6046**

### CODE REVIEW

**Comment by scripthunter7** [comment]
@slavaleleka @piquark6046 since we are moving the compatibility tables, this PR can be closed, do you agree?

**Comment by piquark6046** [comment]
If you want, I agree that.

**Comment by scripthunter7** [comment]
@slavaleleka https://github.com/AdguardTeam/tsurlfilter/blob/master/packages/agtree/src/compatibility-tables/modifiers/inline-script.yml

**Comment by slavaleleka** [comment]
agree

`$inline-script` has already been added
https://github.com/AdguardTeam/tsurlfilter/blob/master/packages/agtree/src/compatibility-tables/modifiers/inline-script.yml

**Pull request closed without merging**
